!macro NSIS_HOOK_PREINSTALL
  ${If} $INSTDIR == "$PROGRAMFILES64\${PRODUCTNAME}"
  ${OrIf} $INSTDIR == "$PROGRAMFILES\${PRODUCTNAME}"
    StrCpy $INSTDIR "$PROGRAMFILES64\EastGeekSMash\${PRODUCTNAME}"
  ${EndIf}
!macroend
