name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Build cleanup
      run: go build -v ./cmd/cleanup/main.go

    - name: Build setup
      run: go build -v ./cmd/setup/main.go

    - name: Test
      run: go test -v ./...
